// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystemAPI.Services.General.Repositories.Data;

#nullable disable

namespace SchoolManagementSystemAPI.Services.General.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240611185551_general-init-db")]
    partial class generalinitdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Assessment", b =>
                {
                    b.Property<string>("AssessmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSchedule")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HourSchedule")
                        .HasColumnType("int");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MinuteSchedule")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssessmentId");

                    b.HasIndex("LessonId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Assignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadlineHour")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineMinute")
                        .HasColumnType("int");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("LessonId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.AttendanceDetail", b =>
                {
                    b.Property<string>("AttendanceDate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttendanceHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttendanceTimeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceTimeOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceDate", "UserId");

                    b.HasIndex("AttendanceHeaderId");

                    b.ToTable("AttendanceDetail");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.AttendanceHeader", b =>
                {
                    b.Property<string>("AttendanceHeaderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<int>("TotalExpectedAttendance")
                        .HasColumnType("int");

                    b.HasKey("AttendanceHeaderId");

                    b.ToTable("AttendanceHeader");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Discussion", b =>
                {
                    b.Property<string>("DisscusionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiscussionDisscusionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DissusionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisscusionId");

                    b.HasIndex("DiscussionDisscusionId");

                    b.HasIndex("LessonId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Event", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventHour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventMinute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("SessionName");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Grade", b =>
                {
                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeNumber");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", b =>
                {
                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("SubjectTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeNumber", "SubjectTitle");

                    b.HasIndex("SubjectTitle");

                    b.ToTable("GradeSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", b =>
                {
                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("TopicId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.LessonQuestion", b =>
                {
                    b.Property<string>("LessonQuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonQuestionId");

                    b.HasIndex("LessonId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.ToTable("LessonQuestions");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Note", b =>
                {
                    b.Property<string>("NoteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.HasIndex("LessonId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Session", b =>
                {
                    b.Property<string>("SessionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SessionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionName");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Subject", b =>
                {
                    b.Property<string>("SubjectTitle")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectTitle");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Term", b =>
                {
                    b.Property<string>("SessionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("TermEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TermStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermStatus")
                        .HasColumnType("int");

                    b.HasKey("SessionName", "TermNumber");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeSubjectGradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeSubjectSubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TermSessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TermTermNumber")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.HasIndex("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle");

                    b.HasIndex("TermSessionName", "TermTermNumber");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Webinar", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("WebinarDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebinarHour")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherInCharge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebinarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebinarMinute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId", "WebinarDate", "WebinarHour");

                    b.ToTable("Webinars");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Assessment", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany()
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Assignment", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany()
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.AttendanceDetail", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.AttendanceHeader", "AttendanceHeader")
                        .WithMany("AttendanceDetails")
                        .HasForeignKey("AttendanceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceHeader");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Discussion", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Discussion", null)
                        .WithMany("DiscussionReplies")
                        .HasForeignKey("DiscussionDisscusionId");

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany("Discussions")
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Event", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Topic", "Topic")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.LessonQuestion", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany()
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Note", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany()
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Term", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Topic", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", "GradeSubject")
                        .WithMany("Topics")
                        .HasForeignKey("GradeSubjectGradeNumber", "GradeSubjectSubjectTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Term", "Term")
                        .WithMany("Topics")
                        .HasForeignKey("TermSessionName", "TermTermNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeSubject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Webinar", b =>
                {
                    b.HasOne("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Topic", "Topic")
                        .WithMany("Webinars")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.AttendanceHeader", b =>
                {
                    b.Navigation("AttendanceDetails");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Discussion", b =>
                {
                    b.Navigation("DiscussionReplies");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.GradeSubject", b =>
                {
                    b.Navigation("Discussions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Term", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.General.Repositories.Schema.Topic", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Webinars");
                });
#pragma warning restore 612, 618
        }
    }
}
