// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystemAPI.Services.SchoolUtils.Repositories.Data;

#nullable disable

namespace SchoolManagementSystemAPI.Services.SchoolUtils.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.SchoolUtils.Repositories.Schema.ClassSubject", b =>
                {
                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("SubjectTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeNumber", "SubjectTitle");

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.SchoolUtils.Repositories.Schema.Grade", b =>
                {
                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeNumber");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.SchoolUtils.Repositories.Schema.Session", b =>
                {
                    b.Property<string>("SessionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SessionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionName");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.SchoolUtils.Repositories.Schema.Subject", b =>
                {
                    b.Property<string>("SubjectTitle")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectTitle");

                    b.ToTable("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
