// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystemAPI.Services.Parent.Repositories.Data;

#nullable disable

namespace SchoolManagementSystemAPI.Services.Parent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240119103713_parent")]
    partial class parent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystemAPI.Services.Parent.Repositories.ParentSchema", b =>
                {
                    b.Property<string>("RegId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegId");

                    b.ToTable("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
